name: Release
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: write
      id-token: write
    env:
      NPM_CONFIG_PROVENANCE: "true"
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/@halkeye/gatsby-theme-nodeschool-example/public

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          working-directory: ./packages/gatsby-theme-nodeschool
